<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content p-5">
        <h1 class="text-center">Conditions of Use :</h1>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corporis fuga qui sint modi expedita laudantium laboriosam consequuntur iste iure harum dolores, maxime autem magni illum fugiat labore, nihil odit velit neque eius, quidem veniam. Optio corrupti dolorum inventore molestias eveniet delectus eos, quisquam porro at iure velit, obcaecati nemo aliquam laborum consectetur! Molestiae dolores dolorum minima est, accusamus mollitia! Consequatur sequi, voluptates vero quidem quia asperiores tenetur rem deserunt ad incidunt ex neque fuga voluptate architecto suscipit aut amet id hic beatae. Illo vero, doloremque incidunt delectus necessitatibus veritatis aspernatur quas amet, porro unde perferendis ut praesentium maiores qui labore neque ratione pariatur quibusdam consectetur dicta! Magnam nihil accusantium culpa neque aut, quos voluptatum. Labore nihil natus optio hic inventore quas, rem id dolores. Aliquid esse laborum possimus quam incidunt, qui pariatur temporibus necessitatibus illo quisquam facilis fugit magnam quo tenetur veritatis, accusamus doloremque iste, impedit ab cum exercitationem. Quasi saepe dolorum iure reiciendis vero rem .</p>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur, libero enim! Sed optio mollitia aspernatur eaque dolorem voluptates debitis laudantium voluptatibus repellendus error molestias ullam delectus animi odit, atque iusto nesciunt cumque excepturi reprehenderit quisquam. Voluptatum in officiis autem delectus quae ab sapiente quo corporis, laborum eos voluptates sint quis velit commodi illum dignissimos vero nihil libero nam error? Tenetur veniam distinctio voluptatibus. In commodi incidunt, repellendus ipsum, dolores perferendis nobis corrupti ipsa minus debitis, eligendi quas modi excepturi corporis. Animi architecto eveniet quae officia et dolorem, accusantium sapiente praesentium magnam odit cupiditate laborum repellendus ipsum amet. Id, laudantium cumque?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates possimus sequi odit nobis omnis quidem blanditiis. Voluptas exercitationem repellendus dolorum asperiores hic repellat rerum voluptatum molestias aperiam, quia sint animi mollitia fuga eum totam repudiandae reiciendis nobis! Facilis, animi eaque ut, perferendis beatae, pariatur vel veritatis ullam omnis necessitatibus dolor.</p>
      </div>
    </div>
  </div>